USE [master]
GO

/****** Object:  Database [telecom_provider]    Script Date: 09/05/2024 21:59:52 ******/
CREATE DATABASE [telecom_provider]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'telecom_provider', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\telecom_provider.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'telecom_provider_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\telecom_provider_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [telecom_provider].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [telecom_provider] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [telecom_provider] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [telecom_provider] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [telecom_provider] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [telecom_provider] SET ARITHABORT OFF 
GO

ALTER DATABASE [telecom_provider] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [telecom_provider] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [telecom_provider] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [telecom_provider] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [telecom_provider] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [telecom_provider] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [telecom_provider] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [telecom_provider] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [telecom_provider] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [telecom_provider] SET  DISABLE_BROKER 
GO

ALTER DATABASE [telecom_provider] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [telecom_provider] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [telecom_provider] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [telecom_provider] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [telecom_provider] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [telecom_provider] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [telecom_provider] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [telecom_provider] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [telecom_provider] SET  MULTI_USER 
GO

ALTER DATABASE [telecom_provider] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [telecom_provider] SET DB_CHAINING OFF 
GO

ALTER DATABASE [telecom_provider] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [telecom_provider] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [telecom_provider] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [telecom_provider] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [telecom_provider] SET QUERY_STORE = OFF
GO

ALTER DATABASE [telecom_provider] SET  READ_WRITE 
GO

